name: Dependencies Report

on:
  pull_request:
    paths:
      - 'tchalanet-web/**'
      - 'tchalanet-server/**'
      - 'tchalanet-mobile/**'
      - '.github/workflows/deps-report.yml'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Web (npm)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'tchalanet-web/package-lock.json'
      - name: npm ci (web)
        working-directory: tchalanet-web
        run: npm ci
      - name: npm outdated
        working-directory: tchalanet-web
        run: |
          echo "== npm outdated =="
          npm outdated || true
      - name: ncu (npm-check-updates) dry-run
        working-directory: tchalanet-web
        run: |
          npx npm-check-updates --target minor --jsonUpgraded || true

      # Server (Maven)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Maven versions plugin
        working-directory: tchalanet-server
        run: |
          ./mvnw -q versions:display-dependency-updates versions:display-plugin-updates

      # Mobile (Flutter)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - name: Pub outdated
        working-directory: tchalanet-mobile
        run: |
          dart pub outdated || true

      # Commentaire PR (résumé)
      - name: Comment PR with summary
        uses: actions/github-script@v7
        with:
          script: |
            const body = `
            ### Dependencies Report
            - Web: ran \`npm outdated\` and \`npm-check-updates --target minor\`
            - Server: ran \`mvn versions:display-dependency-updates\`
            - Mobile: ran \`dart pub outdated\`

            Consultez les logs du job pour les détails des upgrades proposés.
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
