server:
  port: 8083
app:
  cors:
    allowed-origins: https://app.localtest.me,https://auth.localtest.me,http://localhost:4200
  apiBaseUrl: ${APP_API_BASEURL:http://localhost:8083}

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.localtest.me/realms/tchalanet
  datasource:
    url: jdbc:postgresql://localhost:5432/tchalanet_db
  data:
    redis:
      host: localhost
      port: 6379
      password: devredis
