server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tchalanet_db}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app_pwd}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://localhost:8080/realms/tchalanet}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000

tchalanet:
  search:
    meili:
      host: ${MEILI_HOST:http://meilisearch:7700}
      masterKey: ${MEILI_MASTER_KEY:dev-meili}
      index: ${MEILI_INDEX:tch_content}

  web:
    cors:
      allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8081,http://localhost:8082}
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      allowed-headers: Authorization,Content-Type,Accept,Origin
      exposed-headers: Location
      allow-credentials: true
app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}
  version: ${APP_VERSION:0.1.0}
  api-version: ${API_VERSION:v1}
  api-base-url: ${APP_API_BASEURL:http://localhost:8081}
  auth-url: ${OIDC_ISSUER_URI:http://localhost:8080/realms/tchalanet}
  base-path: ${APP_BASE_PATH:/api}
  default-tenant: ${APP_DEFAULT_TENANT:tchalanet}
  security:
    required-audience: tchalanet-api

springdoc:
  api-docs:
    path: /openapi
    enabled: true
  swagger-ui:
    path: /swagger-ui
    oauth:
      client-id: ${SWAGGER_CLIENT_ID:tchalanet-swagger}
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: http://localhost:8082/swagger-ui/oauth2-redirect.html
    display-operation-id: true
    try-it-out-enabled: true
    filter: true

logging:
  config: classpath:logback-spring.xml
  # Default log level for all loggers. (e.g., INFO, DEBUG, WARN, ERROR)
  level:
    # Set the root logger level
    root: INFO
    # Set the level for your application's packages
    com.tchalanet.server: DEBUG
    # Set the level for specific Spring packages (useful for debugging)
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG # To see generated SQL queries