http:
  middlewares:
    secure-headers:
      headers:
        stsSeconds: 15552000
        stsIncludeSubdomains: true
        stsPreload: true
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: "no-referrer-when-downgrade"
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"

    kc-iframe:
      headers:
        frameDeny: false
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"

    gzip:
      compress: {}
