http:
  middlewares:
    secure-headers:
      headers:
        stsSeconds: 15552000
        stsIncludeSubdomains: true
        stsPreload: true
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: "no-referrer-when-downgrade"
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"

    gzip:
      compress: {}
