package com.tchalanet.server.core.reconciliation.internal.domain.model;

public enum ReconciliationAnomalyType {
    DRAW_WINNER_COUNT_MISMATCH,
    DRAW_PAYOUT_TOTAL_MISMATCH,
    DRAW_PAID_TOTAL_EXCEEDS_EXPECTED,
    TICKET_RESULT_STATUS_MISSING_AFTER_DRAW_RESULT,
    EXPECTED_WINNER_NOT_RESULTED,
    FALSE_WINNER_RESULTED,
    SALES_OUTCOME_AMOUNT_MISMATCH,
    WINNER_WITHOUT_PAYOUT_CLAIM,
    CLAIM_FOR_NON_WINNING_TICKET,
    PAYOUT_CLAIM_AMOUNT_MISMATCH,
    PAYMENT_EXCEEDS_CLAIM_AMOUNT,
    PAYMENT_CLAIM_STATUS_MISMATCH,
    PAID_NON_WINNING_TICKET
}
