-- Baseline: Envers revision and audit tables
CREATE SEQUENCE tch_revinfo_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE revinfo
(
    rev               integer PRIMARY KEY DEFAULT nextval('tch_revinfo_seq'),
    rev_timestamp     bigint  NOT NULL,
    tenant_id         uuid,
    user_id           uuid,
    request_id        varchar(128),
    actor_type        varchar(32),
    api_scope         varchar(32),
    tenant_overridden boolean NOT NULL    DEFAULT false
);

CREATE TABLE app_user_aud
(
    id            uuid    NOT NULL,
    rev           integer NOT NULL,
    revtype       smallint,
    created_at    timestamptz,
    created_by    uuid,
    updated_at    timestamptz,
    updated_by    uuid,
    deleted_at    timestamptz,
    deleted_by    uuid,
    version       bigint,
    tenant_id     uuid,
    keycloak_sub  uuid,
    username      text,
    email         citext,
    phone         text,
    first_name    text,
    last_name     text,
    display_name  text,
    avatar_url    text,
    status        varchar(32),
    approved_at   timestamptz,
    approved_by   uuid,
    last_login_at timestamptz,
    CONSTRAINT pk_app_user_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_app_user_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE app_role_aud
(
    id             uuid    NOT NULL,
    rev            integer NOT NULL,
    revtype        smallint,
    created_at     timestamptz,
    created_by     uuid,
    updated_at     timestamptz,
    updated_by     uuid,
    deleted_at     timestamptz,
    deleted_by     uuid,
    version        bigint,
    tenant_id      uuid,
    code           varchar(64),
    name           varchar(128),
    description    text,
    parent_role_id uuid,
    CONSTRAINT pk_app_role_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_app_role_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE permission_aud
(
    code        varchar(128) NOT NULL,
    rev         integer      NOT NULL,
    revtype     smallint,
    created_at  timestamptz,
    created_by  uuid,
    updated_at  timestamptz,
    updated_by  uuid,
    deleted_at  timestamptz,
    deleted_by  uuid,
    version     bigint,
    tenant_id   uuid,
    name        varchar(128),
    category    varchar(64),
    description text,
    CONSTRAINT pk_permission_aud PRIMARY KEY (code, rev),
    CONSTRAINT fk_permission_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE tenant_user_aud
(
    id          uuid    NOT NULL,
    rev         integer NOT NULL,
    revtype     smallint,
    created_at  timestamptz,
    created_by  uuid,
    updated_at  timestamptz,
    updated_by  uuid,
    deleted_at  timestamptz,
    deleted_by  uuid,
    version     bigint,
    tenant_id   uuid,
    user_id     uuid,
    role_id     uuid,
    status      varchar(32),
    is_owner    boolean,
    outlet_id   uuid,
    terminal_id uuid,
    CONSTRAINT pk_tenant_user_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_tenant_user_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE user_preference_aud
(
    id         uuid    NOT NULL,
    rev        integer NOT NULL,
    revtype    smallint,
    created_at timestamptz,
    created_by uuid,
    updated_at timestamptz,
    updated_by uuid,
    deleted_at timestamptz,
    deleted_by uuid,
    version    bigint,
    user_id    uuid,
    theme_mode varchar(10),
    density    smallint,
    locale     varchar(8),
    time_zone  varchar(64),
    currency   varchar(3),
    CONSTRAINT pk_user_preference_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_user_preference_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE app_setting_aud
(
    id            uuid    NOT NULL,
    rev           integer NOT NULL,
    revtype       smallint,
    created_at    timestamptz,
    created_by    uuid,
    updated_at    timestamptz,
    updated_by    uuid,
    deleted_at    timestamptz,
    deleted_by    uuid,
    version       bigint,
    tenant_id     uuid,
    outlet_id     uuid,
    terminal_id   uuid,
    namespace     varchar(255),
    setting_key   varchar(255),
    setting_value text,
    value_type    varchar(50),
    level         varchar(50),
    exposure      varchar(50),
    active        boolean,
    CONSTRAINT pk_app_setting_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_app_setting_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE i18n_override_aud
(
    id         uuid    NOT NULL,
    rev        integer NOT NULL,
    revtype    smallint,
    created_at timestamptz,
    created_by uuid,
    updated_at timestamptz,
    updated_by uuid,
    deleted_at timestamptz,
    deleted_by uuid,
    version    bigint,
    tenant_id  uuid,
    level      varchar(32),
    surface    varchar(50),
    locale     varchar(10),
    i18n_key   varchar(255),
    i18n_value text,
    active     boolean,
    CONSTRAINT pk_i18n_override_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_i18n_override_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE theme_preset_aud
(
    id         uuid    NOT NULL,
    rev        integer NOT NULL,
    revtype    smallint,
    created_at timestamptz,
    created_by uuid,
    updated_at timestamptz,
    updated_by uuid,
    deleted_at timestamptz,
    deleted_by uuid,
    version    bigint,
    tenant_id  uuid,
    code       varchar(128),
    vendor     varchar(128),
    config     text,
    label_key  varchar(255),
    active     boolean,
    is_default boolean,
    CONSTRAINT pk_theme_preset_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_theme_preset_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE game_aud
(
    id          uuid    NOT NULL,
    rev         integer NOT NULL,
    revtype     smallint,
    created_at  timestamptz,
    created_by  uuid,
    updated_at  timestamptz,
    updated_by  uuid,
    deleted_at  timestamptz,
    deleted_by  uuid,
    version     bigint,
    tenant_id   uuid,
    code        varchar(32),
    name        varchar(128),
    category    varchar(32),
    combination varchar(32),
    min_digits  integer,
    max_digits  integer,
    description text,
    active      boolean,
    sort_order  integer,
    CONSTRAINT pk_game_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_game_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE result_slot_aud
(
    id             uuid    NOT NULL,
    rev            integer NOT NULL,
    revtype        smallint,
    created_at     timestamptz,
    created_by     uuid,
    updated_at     timestamptz,
    updated_by     uuid,
    deleted_at     timestamptz,
    deleted_by     uuid,
    version        bigint,
    tenant_id      uuid,
    slot_key       varchar(32),
    provider       varchar(16),
    timezone       varchar(64),
    draw_time      time,
    days_of_week   varchar(32),
    active         boolean,
    sort_order     integer,
    source_cfg     jsonb,
    projection_cfg jsonb,
    notes          text,
    label_key      varchar(256),
    CONSTRAINT pk_result_slot_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_result_slot_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE draw_channel_aud
(
    id              uuid    NOT NULL,
    rev             integer NOT NULL,
    revtype         smallint,
    created_at      timestamptz,
    created_by      uuid,
    updated_at      timestamptz,
    updated_by      uuid,
    deleted_at      timestamptz,
    deleted_by      uuid,
    version         bigint,
    tenant_id       uuid,
    code            varchar(64),
    name            varchar(128),
    period varchar (32),
    timezone        varchar(64),
    draw_time       time,
    sales_open_time time,
    cutoff_sec      integer,
    days_of_week    varchar(32),
    active          boolean,
    sort_order      integer,
    flags           jsonb,
    notes           text,
    result_slot_id  uuid,
    CONSTRAINT pk_draw_channel_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_draw_channel_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE draw_channel_game_aud
(
    id              uuid    NOT NULL,
    rev             integer NOT NULL,
    revtype         smallint,
    created_at      timestamptz,
    created_by      uuid,
    updated_at      timestamptz,
    updated_by      uuid,
    deleted_at      timestamptz,
    deleted_by      uuid,
    version         bigint,
    tenant_id       uuid,
    draw_channel_id uuid,
    game_id         uuid,
    enabled         boolean,
    flags           jsonb,
    CONSTRAINT pk_draw_channel_game_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_draw_channel_game_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE draw_result_aud
(
    id              uuid    NOT NULL,
    rev             integer NOT NULL,
    revtype         smallint,
    created_at      timestamptz,
    created_by      uuid,
    updated_at      timestamptz,
    updated_by      uuid,
    deleted_at      timestamptz,
    deleted_by      uuid,
    version         bigint,
    tenant_id       uuid,
    result_slot_id  uuid,
    occurred_at     timestamptz,
    source_result   jsonb,
    haiti_result    jsonb,
    raw_payload     jsonb,
    flags           jsonb,
    status          varchar(16),
    quality         varchar(16),
    source          varchar(32),
    source_hash     varchar(64),
    fetched_at      timestamptz,
    override_reason text,
    CONSTRAINT pk_draw_result_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_draw_result_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE draw_aud
(
    id                     uuid    NOT NULL,
    rev                    integer NOT NULL,
    revtype                smallint,
    created_at             timestamptz,
    created_by             uuid,
    updated_at             timestamptz,
    updated_by             uuid,
    deleted_at             timestamptz,
    deleted_by             uuid,
    version                bigint,
    tenant_id              uuid,
    draw_channel_id        uuid,
    draw_date              date,
    scheduled_at           timestamptz,
    cutoff_at              timestamptz,
    opened_at              timestamptz,
    closed_at              timestamptz,
    resulted_at            timestamptz,
    settled_at             timestamptz,
    canceled_at            timestamptz,
    cancel_reason_code     varchar(96),
    cancel_reason_label    varchar(255),
    status                 varchar(16),
    draw_result_id         uuid,
    system_generated       boolean,
    locked                 boolean,
    result_source          varchar(16),
    result_override_reason text,
    result_overridden_at   timestamptz,
    CONSTRAINT pk_draw_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_draw_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE pricing_odds_aud
(
    id         uuid    NOT NULL,
    rev        integer NOT NULL,
    revtype    smallint,
    created_at timestamptz,
    created_by uuid,
    updated_at timestamptz,
    updated_by uuid,
    deleted_at timestamptz,
    deleted_by uuid,
    version    bigint,
    tenant_id  uuid,
    game_code  varchar(32),
    bet_type   varchar(32),
    bet_option smallint,
    odds       numeric(12, 4),
    active     boolean,
    CONSTRAINT pk_pricing_odds_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_pricing_odds_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE limit_assignment_aud
(
    id         uuid    NOT NULL,
    rev        integer NOT NULL,
    revtype    smallint,
    tenant_id  uuid,
    rule_key   varchar(80),
    scope_type varchar(32),
    scope_id   uuid,
    enabled    boolean,
    on_breach  varchar(32),
    params     jsonb,
    starts_at  timestamptz,
    ends_at    timestamptz,
    created_at timestamptz,
    created_by uuid,
    updated_at timestamptz,
    updated_by uuid,
    deleted_at timestamptz,
    deleted_by uuid,
    version    bigint,
    CONSTRAINT pk_limit_assignment_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_limit_assignment_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE billing_plan_aud
(
    id             uuid    NOT NULL,
    rev            integer NOT NULL,
    revtype        smallint,
    created_at     timestamptz,
    created_by     uuid,
    updated_at     timestamptz,
    updated_by     uuid,
    deleted_at     timestamptz,
    deleted_by     uuid,
    version        bigint,
    tenant_id      uuid,
    code           varchar(128),
    name           varchar(255),
    description    text,
    price_amount   numeric(19, 2),
    currency       varchar(3),
    billing_period varchar(50),
    limits_json    jsonb,
    features_json  jsonb,
    active         boolean,
    is_default     boolean,
    CONSTRAINT pk_billing_plan_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_billing_plan_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE tenant_subscription_aud
(
    id            uuid    NOT NULL,
    rev           integer NOT NULL,
    revtype       smallint,
    created_at    timestamptz,
    created_by    uuid,
    updated_at    timestamptz,
    updated_by    uuid,
    deleted_at    timestamptz,
    deleted_by    uuid,
    version       bigint,
    tenant_id     uuid,
    plan_code     varchar(128),
    status        varchar(50),
    started_at    timestamptz,
    ends_at       timestamptz,
    trial_ends_at timestamptz,
    canceled_at   timestamptz,
    metadata_json jsonb,
    CONSTRAINT pk_tenant_subscription_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_tenant_subscription_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE page_model_template_aud
(
    id             uuid    NOT NULL,
    rev            integer NOT NULL,
    revtype        smallint,
    created_at     timestamptz,
    created_by     uuid,
    updated_at     timestamptz,
    updated_by     uuid,
    deleted_at     timestamptz,
    deleted_by     uuid,
    version        bigint,
    scope          varchar(32),
    slug           varchar(128),
    tenant_id      uuid,
    code           varchar(128),
    logical_id     varchar(255),
    name           varchar(255),
    label          varchar(255),
    description    text,
    schema         jsonb,
    model          jsonb,
    schema_version integer,
    is_default     boolean,
    level          varchar(16),
    CONSTRAINT pk_page_model_template_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_page_model_template_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE page_model_aud
(
    id             uuid    NOT NULL,
    rev            integer NOT NULL,
    revtype        smallint,
    created_at     timestamptz,
    created_by     uuid,
    updated_at     timestamptz,
    updated_by     uuid,
    deleted_at     timestamptz,
    deleted_by     uuid,
    version        bigint,
    tenant_id      uuid,
    code           varchar(128),
    logical_id     varchar(255),
    name           varchar(255),
    schema         jsonb,
    scope          varchar(255),
    slug           varchar(255),
    schema_version integer,
    model          jsonb,
    status         varchar(255),
    published_at   timestamptz,
    template_id    uuid,
    active         boolean,
    CONSTRAINT pk_page_model_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_page_model_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE notification_aud
(
    id             uuid    NOT NULL,
    rev            integer NOT NULL,
    revtype        smallint,
    created_at     timestamptz,
    created_by     uuid,
    updated_at     timestamptz,
    updated_by     uuid,
    deleted_at     timestamptz,
    deleted_by     uuid,
    version        bigint,
    tenant_id      uuid,
    source_type    varchar(96),
    source_id      varchar(160),
    dedupe_key     varchar(240),
    audience_type  varchar(32),
    audience_value varchar(160),
    severity       varchar(32),
    kind           varchar(32),
    category       varchar(48),
    title_key      varchar(255),
    message_key    varchar(255),
    title_text     varchar(512),
    message_text   varchar(4000),
    payload        jsonb,
    action_type    varchar(96),
    action_url     varchar(1024),
    status         varchar(32),
    read_at        timestamptz,
    archived_at    timestamptz,
    expires_at     timestamptz,
    CONSTRAINT pk_notification_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_notification_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE notification_delivery_aud
(
    id                  uuid    NOT NULL,
    rev                 integer NOT NULL,
    revtype             smallint,
    created_at          timestamptz,
    created_by          uuid,
    updated_at          timestamptz,
    updated_by          uuid,
    deleted_at          timestamptz,
    deleted_by          uuid,
    version             bigint,
    tenant_id           uuid,
    notification_id     uuid,
    channel             varchar(32),
    recipient           varchar(255),
    status              varchar(32),
    attempt_count       integer,
    next_attempt_at     timestamptz,
    last_attempt_at     timestamptz,
    provider            varchar(96),
    provider_message_id varchar(160),
    error_code          varchar(96),
    error_message       varchar(1000),
    payload             jsonb,
    CONSTRAINT pk_notification_delivery_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_notification_delivery_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE notification_preference_aud
(
    id          uuid    NOT NULL,
    rev         integer NOT NULL,
    revtype     smallint,
    created_at  timestamptz,
    created_by  uuid,
    updated_at  timestamptz,
    updated_by  uuid,
    deleted_at  timestamptz,
    deleted_by  uuid,
    version     bigint,
    tenant_id   uuid,
    scope_type  varchar(32),
    scope_value varchar(160),
    category    varchar(48),
    kind        varchar(32),
    channel     varchar(32),
    enabled     boolean,
    CONSTRAINT pk_notification_preference_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_notification_preference_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
CREATE TABLE notification_template_aud
(
    id             uuid    NOT NULL,
    rev            integer NOT NULL,
    revtype        smallint,
    created_at     timestamptz,
    created_by     uuid,
    updated_at     timestamptz,
    updated_by     uuid,
    deleted_at     timestamptz,
    deleted_by     uuid,
    version        bigint,
    tenant_id      uuid,
    template_key   varchar(120),
    locale         varchar(20),
    title_template text,
    body_template  text,
    active         boolean,
    CONSTRAINT pk_notification_template_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_notification_template_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE sales_zone_aud
(
    id         uuid    NOT NULL,
    rev        integer NOT NULL,
    revtype    smallint NULL,
    tenant_id  uuid,
    code       varchar(80),
    label      varchar(160),
    active     boolean,
    parent_id  uuid,
    created_at timestamptz,
    created_by uuid,
    updated_at timestamptz,
    updated_by uuid,
    deleted_at timestamptz,
    deleted_by uuid,
    version    bigint,
    CONSTRAINT pk_sales_zone_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_sales_zone_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE outlet_aud
(
    id                          uuid    NOT NULL,
    rev                         integer NOT NULL,
    revtype                     smallint,
    tenant_id                   uuid,
    name                        varchar(255),
    slug                        varchar(128),
    status                      varchar(40),
    -- classification
    kind                        varchar(40),
    partner_ref                 varchar(120),
    zone_id                     uuid,
    metadata_json               jsonb,
    -- day
    day_closed                  boolean,
    -- outlet-level block
    outlet_blocked              boolean,
    outlet_block_reason         text,
    outlet_blocked_at           timestamptz,
    outlet_blocked_by           uuid,
    -- sales block
    sales_blocked               boolean,
    sales_block_reason          text,
    sales_blocked_at            timestamptz,
    sales_blocked_by            uuid,
    -- payout block
    payout_blocked              boolean,
    payout_block_reason         text,
    payout_blocked_at           timestamptz,
    payout_blocked_by           uuid,
    -- offline sales block
    offline_sales_blocked       boolean,
    offline_sales_block_reason  text,
    offline_sales_blocked_at    timestamptz,
    offline_sales_blocked_by    uuid,
    -- config
    timezone                    varchar(64),
    receipt_printing_enabled    boolean,
    receipt_header_message      text,
    receipt_footer_message      text,
    require_opening_float       boolean,
    auto_session_open_enabled   boolean,
    auto_session_close_enabled  boolean,
    session_open_time           time,
    session_close_time          time,
    default_opening_float_cents bigint,
    address_id                  uuid,
    created_at                  timestamptz,
    created_by                  uuid,
    updated_at                  timestamptz,
    updated_by                  uuid,
    deleted_at                  timestamptz,
    deleted_by                  uuid,
    version                     bigint,
    CONSTRAINT pk_outlet_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_outlet_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE terminal_aud
(
    id                   uuid    NOT NULL,
    rev                  integer NOT NULL,
    revtype              smallint,
    tenant_id            uuid,
    outlet_id            uuid,
    assigned_user_id     uuid,
    kind                 varchar(16),
    state                varchar(32),
    auto_session_enabled boolean,
    sync_state           varchar(32),
    last_seen            timestamptz,
    label                varchar(128),
    inventory_tag        varchar(64),
    metadata             jsonb,
    registered_at        timestamptz,
    unregistered_at      timestamptz,
    locked_at            timestamptz,
    locked_by            uuid,
    lock_reason          text,
    value                varchar(80),
    sales_blocked        boolean,
    sales_block_reason   text,
    sales_blocked_at     timestamptz,
    sales_blocked_by     uuid,
    payout_blocked       boolean,
    payout_block_reason  text,
    payout_blocked_at    timestamptz,
    payout_blocked_by    uuid,
    offline_blocked      boolean,
    offline_block_reason text,
    offline_blocked_at   timestamptz,
    offline_blocked_by   uuid,
    created_at           timestamptz,
    created_by           uuid,
    updated_at           timestamptz,
    updated_by           uuid,
    deleted_at           timestamptz,
    deleted_by           uuid,
    version              bigint,
    CONSTRAINT pk_terminal_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_terminal_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE terminal_capability_aud
(
    id          uuid    NOT NULL,
    rev         integer NOT NULL,
    revtype     smallint,
    tenant_id   uuid,
    terminal_id uuid,
    capability  varchar(64),
    created_at  timestamptz,
    created_by  uuid,
    updated_at  timestamptz,
    updated_by  uuid,
    deleted_at  timestamptz,
    deleted_by  uuid,
    version     bigint,
    CONSTRAINT pk_terminal_capability_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_terminal_capability_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE terminal_assignment_aud
(
    id          uuid    NOT NULL,
    rev         integer NOT NULL,
    revtype     smallint,
    tenant_id   uuid,
    terminal_id uuid,
    user_id     uuid,
    status      varchar(32),
    assigned_at timestamptz,
    revoked_at  timestamptz,
    created_at  timestamptz,
    created_by  uuid,
    updated_at  timestamptz,
    updated_by  uuid,
    deleted_at  timestamptz,
    deleted_by  uuid,
    version     bigint,
    CONSTRAINT pk_terminal_assignment_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_terminal_assignment_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE terminal_binding_aud
(
    id                      uuid    NOT NULL,
    rev                     integer NOT NULL,
    revtype                 smallint,
    tenant_id               uuid,
    terminal_id             uuid,
    binding_type            varchar(32),
    status                  varchar(32),
    binding_public_key      text,
    public_key_algorithm    varchar(32),
    public_key_hash         text,
    credential_hash         text,
    device_fingerprint_hash text,
    bound_by                uuid,
    bound_at                timestamptz,
    expires_at              timestamptz,
    revoked_at              timestamptz,
    last_seen_at            timestamptz,
    created_at              timestamptz,
    created_by              uuid,
    updated_at              timestamptz,
    updated_by              uuid,
    deleted_at              timestamptz,
    deleted_by              uuid,
    version                 bigint,
    CONSTRAINT pk_terminal_binding_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_terminal_binding_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE terminal_challenge_aud
(
    id             uuid    NOT NULL,
    rev            integer NOT NULL,
    revtype        smallint,
    tenant_id      uuid,
    terminal_id    uuid,
    user_id        uuid,
    challenge_type varchar(32),
    channel        varchar(32),
    code_hash      text,
    expires_at     timestamptz,
    attempt_count  integer,
    max_attempts   integer,
    status         varchar(32),
    consumed_at    timestamptz,
    cancelled_at   timestamptz,
    created_at     timestamptz,
    created_by     uuid,
    updated_at     timestamptz,
    updated_by     uuid,
    deleted_at     timestamptz,
    deleted_by     uuid,
    version        bigint,
    CONSTRAINT pk_terminal_challenge_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_terminal_challenge_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE sales_session_aud
(
    id                            uuid    NOT NULL,
    rev                           integer NOT NULL,
    revtype                       smallint,
    tenant_id                     uuid,
    outlet_id                     uuid,
    terminal_id                   uuid,
    opened_by                     uuid,
    opened_at                     timestamptz,
    business_date                 date,
    status                        varchar(32),
    closed_by                     uuid,
    closed_at                     timestamptz,
    close_reason                  text,
    opening_float_cents           bigint,
    expected_closing_amount_cents bigint,
    declared_closing_amount_cents bigint,
    variance_cents                bigint,
    finalized_at                  timestamptz,
    finalized_by                  uuid,
    finalize_reason               text,
    created_at                    timestamptz,
    created_by                    uuid,
    updated_at                    timestamptz,
    updated_by                    uuid,
    deleted_at                    timestamptz,
    deleted_by                    uuid,
    version                       bigint,
    CONSTRAINT pk_sales_session_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_sales_session_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE payout_aud
(
    -- Envers metadata
    id                 uuid    NOT NULL,
    rev                integer NOT NULL,
    revtype            smallint,

    -- claim identity
    tenant_id          uuid,
    ticket_id          uuid,
    draw_id            uuid,
    source_event_id    uuid,
    source             varchar(32),

    amount_cents       bigint,
    currency           varchar(3),
    status             varchar(32),

    -- claim opening
    opened_at          timestamptz,

    -- selling context
    selling_outlet_id  uuid,
    selling_session_id uuid,

    -- payment execution
    paying_outlet_id   uuid,
    paying_session_id  uuid,
    paying_terminal_id uuid,
    paid_by            uuid,
    paid_at            timestamptz,

    -- block
    blocked_by         uuid,
    blocked_at         timestamptz,
    block_reason       text,

    -- cancel
    cancelled_by       uuid,
    cancelled_at       timestamptz,
    cancel_reason      text,

    -- reversal
    reversed_by        uuid,
    reversed_at        timestamptz,
    reverse_reason     text,

    -- base audit columns
    created_at         timestamptz,
    created_by         uuid,
    updated_at         timestamptz,
    updated_by         uuid,
    deleted_at         timestamptz,
    deleted_by         uuid,
    version            bigint,

    CONSTRAINT pk_payout_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_payout_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE sales_ticket_aud
(
    id                      uuid    NOT NULL,
    rev                     integer NOT NULL,
    revtype                 smallint,
    tenant_id               uuid,
    outlet_id               uuid,
    terminal_id             uuid,
    seller_user_id          uuid,
    seller_id               uuid,
    seller_assignment_id    uuid,
    sales_session_id        uuid,
    draw_id                 uuid,
    draw_channel_id         uuid,
    payout_id               uuid,
    ticket_code             varchar(64),
    public_code             varchar(32),
    verification_code       varchar(32),
    currency                varchar(3),
    stake_amount            numeric(19, 4),
    total_amount            numeric(19, 4),
    potential_payout_amount numeric(19, 4),
    winning_amount          numeric(19, 4),
    sale_status             varchar(32),
    sold_at                 timestamptz,
    placed_at               timestamptz,
    approval_request_id     uuid,
    approval_requested_by   uuid,
    approval_requested_at   timestamptz,
    approved_at             timestamptz,
    approved_by             uuid,
    rejected_at             timestamptz,
    rejected_by             uuid,
    rejection_reason        varchar(500),
    cancelled_at            timestamptz,
    cancelled_by            uuid,
    cancellation_reason     varchar(500),
    voided_at               timestamptz,
    voided_by               uuid,
    void_reason             varchar(500),
    result_status           varchar(32),
    resulted_at             timestamptz,
    resulted_by             uuid,
    result_override_reason  varchar(500),
    settlement_status       varchar(32),
    settled_at              timestamptz,
    settled_by              uuid,
    paid_at                 timestamptz,
    paid_by                 uuid,
    sale_channel            varchar(32),
    offline_submission_id   uuid,
    offline_batch_id        uuid,
    offline_code_batch_id   uuid,
    offline_code            varchar(64),
    offline_client_sale_id  varchar(64),
    offline_local_sequence  bigint,
    offline_sold_at_device  timestamptz,
    offline_sync_status     varchar(48),
    print_status            varchar(16),
    print_count             integer,
    first_printed_at        timestamptz,
    last_printed_at         timestamptz,
    created_at              timestamptz,
    created_by              uuid,
    updated_at              timestamptz,
    updated_by              uuid,
    deleted_at              timestamptz,
    deleted_by              uuid,
    version                 bigint,
    CONSTRAINT pk_sales_ticket_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_sales_ticket_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE sales_ticket_line_aud
(
    id                      uuid    NOT NULL,
    rev                     integer NOT NULL,
    revtype                 smallint,
    tenant_id               uuid,
    ticket_id               uuid,
    draw_id                 uuid,
    line_number             integer,
    game_code               varchar(64),
    bet_type                varchar(64),
    bet_option              smallint,
    selection_key           varchar(128),
    display_selection       varchar(256),
    stake_amount            numeric(19, 4),
    payout_base_amount      numeric(19, 4),
    odds_snapshot           numeric(19, 6),
    potential_payout_amount numeric(19, 4),
    origin                  varchar(16),
    pricing_source          varchar(16),
    selection_source        varchar(32),
    promotion_decision_id   uuid,
    promotion_label         varchar(128),
    promotion_effect_type   varchar(32),
    result_status           varchar(16),
    payout_amount           numeric(19, 4),
    created_at              timestamptz,
    created_by              uuid,
    updated_at              timestamptz,
    updated_by              uuid,
    deleted_at              timestamptz,
    deleted_by              uuid,
    version                 bigint,
    CONSTRAINT pk_sales_ticket_line_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_sales_ticket_line_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE sales_ticket_charge_aud
(
    id                    uuid    NOT NULL,
    rev                   integer NOT NULL,
    revtype               smallint,
    tenant_id             uuid,
    sales_ticket_id       uuid,
    charge_type           varchar(48),
    paid_by               varchar(16),
    amount                numeric(19, 4),
    currency              varchar(3),
    waived_by_rule_id     uuid,
    waived_by_decision_id uuid,
    waived_effect_type    varchar(64),
    waived_label          varchar(256),
    created_at            timestamptz,
    created_by            uuid,
    updated_at            timestamptz,
    updated_by            uuid,
    deleted_at            timestamptz,
    deleted_by            uuid,
    version               bigint,
    CONSTRAINT pk_sales_ticket_charge_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_sales_ticket_charge_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE offline_grant_aud
(
    id                    uuid    NOT NULL,
    rev                   integer NOT NULL,
    revtype               smallint,
    tenant_id             uuid,
    terminal_id           uuid,
    outlet_id             uuid,
    seller_user_id        uuid,
    sales_session_id      uuid,
    device_id             uuid,
    key_id                varchar(64),
    code_batch_id         uuid,
    status                varchar(32),
    valid_from            timestamptz,
    valid_until           timestamptz,
    sync_accepted_until   timestamptz,
    max_ticket_count      integer,
    max_total_amount      numeric(18, 2),
    currency              varchar(3),
    consumed_ticket_count integer,
    consumed_total_amount numeric(18, 2),
    token_hash            varchar(255),
    issued_at             timestamptz,
    revoked_at            timestamptz,
    revoked_reason        varchar(255),
    created_at            timestamptz,
    created_by            uuid,
    updated_at            timestamptz,
    updated_by            uuid,
    deleted_at            timestamptz,
    deleted_by            uuid,
    version               bigint,
    CONSTRAINT pk_offline_grant_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_offline_grant_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE offline_sync_batch_aud
(
    id                     uuid    NOT NULL,
    rev                    integer NOT NULL,
    revtype                smallint,
    tenant_id              uuid,
    terminal_id            uuid,
    outlet_id              uuid,
    seller_user_id         uuid,
    sales_session_id       uuid,
    device_id              uuid,
    grant_id               uuid,
    code_batch_id          uuid,
    client_batch_id        varchar(255),
    received_at            timestamptz,
    processed_at           timestamptz,
    status                 varchar(32),
    submission_count       integer,
    technical_reject_count integer,
    sales_accept_count     integer,
    sales_reject_count     integer,
    review_count           integer,
    created_at             timestamptz,
    created_by             uuid,
    updated_at             timestamptz,
    updated_by             uuid,
    deleted_at             timestamptz,
    deleted_by             uuid,
    version                bigint,
    CONSTRAINT pk_offline_sync_batch_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_offline_sync_batch_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE offline_code_batch_aud
(
    id              uuid    NOT NULL,
    rev             integer NOT NULL,
    revtype         smallint,
    tenant_id       uuid,
    grant_id        uuid,
    terminal_id     uuid,
    outlet_id       uuid,
    seller_user_id  uuid,
    allocated_count integer,
    consumed_count  integer,
    status          varchar(32),
    issued_at       timestamptz,
    expires_at      timestamptz,
    created_at      timestamptz,
    created_by      uuid,
    updated_at      timestamptz,
    updated_by      uuid,
    deleted_at      timestamptz,
    deleted_by      uuid,
    version         bigint,
    CONSTRAINT pk_offline_code_batch_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_offline_code_batch_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE offline_submission_aud
(
    id                      uuid    NOT NULL,
    rev                     integer NOT NULL,
    revtype                 smallint,
    tenant_id               uuid,
    sync_batch_id           uuid,
    grant_id                uuid,
    code_batch_id           uuid,
    offline_code            varchar(255),
    client_submission_id    varchar(255),
    device_id               uuid,
    seller_user_id          uuid,
    terminal_id             uuid,
    outlet_id               uuid,
    sales_session_id        uuid,
    client_sold_at          timestamptz,
    received_at             timestamptz,
    processed_at            timestamptz,
    status                  varchar(32),
    rejection_code          varchar(64),
    rejection_reason        varchar(500),
    draw_id                 uuid,
    total_stake_amount      numeric(18, 2),
    currency                varchar(3),
    line_count              integer,
    payload_hash            varchar(255),
    signature               varchar(255),
    promotion_attempt_id    uuid,
    promotion_requested_at  timestamptz,
    last_promotion_event_id uuid,
    created_ticket_id       uuid,
    created_at              timestamptz,
    created_by              uuid,
    updated_at              timestamptz,
    updated_by              uuid,
    deleted_at              timestamptz,
    deleted_by              uuid,
    version                 bigint,
    CONSTRAINT pk_offline_submission_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_offline_submission_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE offline_submission_line_aud
(
    id               uuid    NOT NULL,
    rev              integer NOT NULL,
    revtype          smallint,
    tenant_id        uuid,
    submission_id    uuid,
    line_no          integer,
    game_code        varchar(64),
    bet_type         varchar(64),
    bet_option       varchar(64),
    selection_key    varchar(255),
    stake_amount     numeric(18, 2),
    potential_payout numeric(18, 2),
    status           varchar(32),
    rejection_code   varchar(64),
    rejection_reason varchar(500),
    created_at       timestamptz,
    created_by       uuid,
    updated_at       timestamptz,
    updated_by       uuid,
    deleted_at       timestamptz,
    deleted_by       uuid,
    version          bigint,
    CONSTRAINT pk_offline_submission_line_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_offline_submission_line_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE offline_code_aud
(
    id                    uuid    NOT NULL,
    rev                   integer NOT NULL,
    revtype               smallint,
    tenant_id             uuid,
    code_batch_id         uuid,
    grant_id              uuid,
    offline_submission_id uuid,
    ticket_id             uuid,
    code                  varchar(64),
    status                varchar(32),
    reserved_at           timestamptz,
    consumed_at           timestamptz,
    expires_at            timestamptz,
    created_at            timestamptz,
    created_by            uuid,
    updated_at            timestamptz,
    updated_by            uuid,
    deleted_at            timestamptz,
    deleted_by            uuid,
    version               bigint,
    CONSTRAINT pk_offline_code_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_offline_code_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE offline_submission_ticket_link_aud
(
    id            uuid    NOT NULL,
    rev           integer NOT NULL,
    revtype       smallint,
    tenant_id     uuid,
    submission_id uuid,
    ticket_id     uuid,
    link_type     varchar(32),
    linked_at     timestamptz,
    created_at    timestamptz,
    created_by    uuid,
    updated_at    timestamptz,
    updated_by    uuid,
    deleted_at    timestamptz,
    deleted_by    uuid,
    version       bigint,
    CONSTRAINT pk_offline_submission_ticket_link_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_offline_submission_ticket_link_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE sales_session_offline_adjustment_aud
(
    id                 uuid    NOT NULL,
    rev                integer NOT NULL,
    revtype            smallint,
    tenant_id          uuid,
    sales_session_id   uuid,
    ticket_id          uuid,
    amount_cents       bigint,
    currency           varchar(3),
    source             varchar(64),
    reason             varchar(255),
    occurred_at_device timestamptz,
    recorded_at        timestamptz,
    version            bigint,
    CONSTRAINT pk_sales_session_offline_adjustment_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_sales_session_offline_adjustment_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

-- ─── Promotion audit tables ──────────────────────────────────────────
CREATE TABLE promotion_campaign_aud
(
    id             uuid    NOT NULL,
    tenant_id      uuid    NOT NULL,
    rev            integer NOT NULL,
    revtype        smallint NULL,
    code           varchar(96),
    name           varchar(160),
    status         varchar(32),
    priority       integer,
    starts_at      timestamptz,
    ends_at        timestamptz,
    config_version varchar(48),
    created_at     timestamptz,
    created_by     uuid,
    updated_at     timestamptz,
    updated_by     uuid,
    deleted_at     timestamptz,
    deleted_by     uuid,
    version        bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE promotion_rule_aud
(
    id                uuid    NOT NULL,
    tenant_id         uuid    NOT NULL,
    rev               integer NOT NULL,
    revtype           smallint NULL,
    campaign_id       uuid,
    rule_key          varchar(96),
    priority          integer,
    min_paid_total    numeric(19, 4),
    before_local_time time,
    created_at        timestamptz,
    created_by        uuid,
    updated_at        timestamptz,
    updated_by        uuid,
    deleted_at        timestamptz,
    deleted_by        uuid,
    version           bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE promotion_rule_effect_aud
(
    id                 uuid    NOT NULL,
    tenant_id          uuid    NOT NULL,
    rev                integer NOT NULL,
    revtype            smallint NULL,
    rule_id            uuid,
    effect_type        varchar(32),
    game_code          varchar(64),
    payout_base_amount numeric(19, 4),
    quantity           integer,
    odds_override      numeric(19, 6),
    charge_type        varchar(64),
    created_at         timestamptz,
    created_by         uuid,
    updated_at         timestamptz,
    updated_by         uuid,
    deleted_at         timestamptz,
    deleted_by         uuid,
    version            bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE promotion_rule_eligibility_line_aud
(
    id         uuid    NOT NULL,
    tenant_id  uuid    NOT NULL,
    rev        integer NOT NULL,
    revtype    smallint NULL,
    rule_id    uuid,
    game_code  varchar(64),
    min_count  integer,
    created_at timestamptz,
    created_by uuid,
    updated_at timestamptz,
    updated_by uuid,
    deleted_at timestamptz,
    deleted_by uuid,
    version    bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE promotion_decision_aud
(
    id               uuid    NOT NULL,
    tenant_id        uuid    NOT NULL,
    rev              integer NOT NULL,
    revtype          smallint NULL,
    decision_status  varchar(32),
    evaluation_phase varchar(48),
    evaluated_at     timestamptz,
    context_hash     varchar(128),
    engine_version   varchar(48),
    decision_json    jsonb,
    created_at       timestamptz,
    created_by       uuid,
    updated_at       timestamptz,
    updated_by       uuid,
    deleted_at       timestamptz,
    deleted_by       uuid,
    version          bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE applied_promotion_snapshot_aud
(
    id                    uuid    NOT NULL,
    tenant_id             uuid    NOT NULL,
    rev                   integer NOT NULL,
    revtype               smallint NULL,
    ticket_id             uuid,
    promotion_decision_id uuid,
    decision_status       varchar(32),
    applied_at            timestamptz,
    snapshot_json         jsonb,
    created_at            timestamptz,
    created_by            uuid,
    updated_at            timestamptz,
    updated_by            uuid,
    deleted_at            timestamptz,
    deleted_by            uuid,
    version               bigint,
    PRIMARY KEY (id, rev)
);

CREATE TABLE seller_aud
(
    id           uuid    NOT NULL,
    tenant_id    uuid    NOT NULL,
    rev          integer NOT NULL,
    revtype      smallint NULL,
    user_id      uuid,
    code         varchar(80),
    display_name varchar(180),
    status       varchar(24),
    created_at   timestamptz,
    created_by   uuid,
    updated_at   timestamptz,
    updated_by   uuid,
    deleted_at   timestamptz,
    deleted_by   uuid,
    version      bigint,
    CONSTRAINT pk_seller_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_seller_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE seller_outlet_assignment_aud
(
    id         uuid    NOT NULL,
    tenant_id  uuid    NOT NULL,
    rev        integer NOT NULL,
    revtype    smallint NULL,
    seller_id  uuid,
    outlet_id  uuid,
    starts_at  timestamptz,
    ends_at    timestamptz,
    status     varchar(24),
    created_at timestamptz,
    created_by uuid,
    updated_at timestamptz,
    updated_by uuid,
    deleted_at timestamptz,
    deleted_by uuid,
    version    bigint,
    CONSTRAINT pk_seller_outlet_assignment_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_seller_outlet_assignment_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE seller_commission_policy_aud
(
    id              uuid    NOT NULL,
    tenant_id       uuid    NOT NULL,
    rev             integer NOT NULL,
    revtype         smallint NULL,
    seller_id       uuid,
    commission_type varchar(40),
    commission_base varchar(40),
    rate_percent    numeric(8, 4),
    fixed_amount    numeric(18, 4),
    currency        varchar(8),
    starts_at       timestamptz,
    ends_at         timestamptz,
    status          varchar(24),
    created_at      timestamptz,
    created_by      uuid,
    updated_at      timestamptz,
    updated_by      uuid,
    deleted_at      timestamptz,
    deleted_by      uuid,
    version         bigint,
    CONSTRAINT pk_seller_commission_policy_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_seller_commission_policy_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
