-- Baseline: Envers revision and audit tables
CREATE SEQUENCE tch_revinfo_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE revinfo (
  rev integer PRIMARY KEY DEFAULT nextval('tch_revinfo_seq'),
  rev_timestamp bigint NOT NULL,
  tenant_id uuid,
  user_id uuid,
  request_id varchar(128),
  actor_type varchar(32),
  api_scope varchar(32),
  tenant_overridden boolean NOT NULL DEFAULT false
);

CREATE TABLE app_user_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, keycloak_sub uuid, username text, email citext, phone text, first_name text, last_name text, display_name text, avatar_url text, status varchar(32), approved_at timestamptz, approved_by uuid, last_login_at timestamptz, CONSTRAINT pk_app_user_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_app_user_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE app_role_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, code varchar(64), name varchar(128), description text, parent_role_id uuid, CONSTRAINT pk_app_role_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_app_role_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE permission_aud (code varchar(128) NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, name varchar(128), category varchar(64), description text, CONSTRAINT pk_permission_aud PRIMARY KEY (code, rev),
  CONSTRAINT fk_permission_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE tenant_user_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, user_id uuid, role_id uuid, status varchar(32), is_owner boolean, outlet_id uuid, terminal_id uuid, CONSTRAINT pk_tenant_user_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_tenant_user_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE user_preference_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, user_id uuid, theme_mode varchar(10), density smallint, locale varchar(8), time_zone varchar(64), currency varchar(3), CONSTRAINT pk_user_preference_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_user_preference_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE app_setting_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, outlet_id uuid, terminal_id uuid, namespace varchar(255), setting_key varchar(255), setting_value text, value_type varchar(50), level varchar(50), active boolean, CONSTRAINT pk_app_setting_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_app_setting_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE i18n_override_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, level varchar(32), locale varchar(10), i18n_key varchar(255), i18n_value text, active boolean, CONSTRAINT pk_i18n_override_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_i18n_override_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE theme_preset_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, code varchar(128), vendor varchar(128), config text, label_key varchar(255), active boolean, is_default boolean, CONSTRAINT pk_theme_preset_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_theme_preset_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE outlet_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, address_id uuid, name text, slug citext, day_closed boolean, sales_blocked boolean, sales_block_reason text, sales_blocked_at timestamptz, timezone varchar(64), business_day_cutoff time, receipt_printing_enabled boolean, receipt_header_message text, receipt_footer_message text, require_opening_float boolean, auto_open_session boolean, auto_close_session boolean, auto_session_user_id uuid, auto_session_terminal_id uuid, default_opening_float_cents bigint, CONSTRAINT pk_outlet_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_outlet_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE terminal_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, outlet_id uuid, assigned_user_id uuid, kind varchar(16), state varchar(32), active_for_user boolean, last_seen timestamptz, label varchar(128), inventory_tag varchar(64), metadata jsonb, sync_state varchar(32), registered_at timestamptz, unregistered_at timestamptz, locked_at timestamptz, locked_by uuid, lock_reason text, CONSTRAINT pk_terminal_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_terminal_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE sales_session_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, outlet_id uuid, terminal_id uuid, user_id uuid, status varchar(16), source varchar(16), opened_at timestamptz, closed_at timestamptz, opening_float_cents bigint, closing_amount_cents bigint, meta jsonb, CONSTRAINT pk_sales_session_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_sales_session_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE sales_session_totals_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, session_id uuid, total_tickets bigint, total_stake_cents bigint, total_payout_cents bigint, gross_margin_cents bigint, last_recomputed_at timestamptz, CONSTRAINT pk_sales_session_totals_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_sales_session_totals_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE game_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, code varchar(32), name varchar(128), category varchar(32), combination varchar(32), min_digits integer, max_digits integer, description text, active boolean, sort_order integer, CONSTRAINT pk_game_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_game_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE result_slot_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, slot_key varchar(32), provider varchar(16), timezone varchar(64), draw_time time, days_of_week varchar(32), active boolean, sort_order integer, source_cfg jsonb, projection_cfg jsonb, notes text, label_key varchar(256), CONSTRAINT pk_result_slot_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_result_slot_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE draw_channel_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, code varchar(64), name varchar(128), period varchar(32), timezone varchar(64), draw_time time, sales_open_time time, cutoff_sec integer, days_of_week varchar(32), active boolean, sort_order integer, flags jsonb, notes text, result_slot_id uuid, CONSTRAINT pk_draw_channel_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_draw_channel_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE draw_channel_game_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, draw_channel_id uuid, game_id uuid, enabled boolean, flags jsonb, CONSTRAINT pk_draw_channel_game_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_draw_channel_game_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE draw_result_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, result_slot_id uuid, occurred_at timestamptz, source_result jsonb, haiti_result jsonb, raw_payload jsonb, flags jsonb, status varchar(16), quality varchar(16), source varchar(32), source_hash varchar(64), fetched_at timestamptz, override_reason text, CONSTRAINT pk_draw_result_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_draw_result_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE draw_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, draw_channel_id uuid, draw_date date, scheduled_at timestamptz, cutoff_at timestamptz, opened_at timestamptz, closed_at timestamptz, resulted_at timestamptz, settled_at timestamptz, canceled_at timestamptz, cancel_reason text, status varchar(16), draw_result_id uuid, system_generated boolean, locked boolean, result_source varchar(16), result_override_reason text, result_overridden_at timestamptz, CONSTRAINT pk_draw_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_draw_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE ticket_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, outlet_id uuid, terminal_id uuid, draw_id uuid, session_id uuid, user_id uuid, ticket_code text, public_code varchar(32), sale_status varchar(24), result_status varchar(24), settlement_status varchar(24), currency varchar(3), total_amount_cents bigint, winning_amount_cents bigint, resulted_at timestamptz, approval_request_id uuid, CONSTRAINT pk_ticket_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_ticket_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE ticket_line_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, ticket_id uuid, game_code varchar(32), selection varchar(32), stake_cents bigint, odds_snapshot numeric(12,4), potential_payout_cents bigint, bet_option smallint, bet_type varchar(32), CONSTRAINT pk_ticket_line_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_ticket_line_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));

create table payout_aud (
                            id uuid not null,
                            rev integer not null,
                            revtype smallint,

                            tenant_id uuid,

                            ticket_id uuid,
                            amount_cents bigint,
                            currency varchar(3),

                            status varchar(32),

                            selling_outlet_id uuid,
                            selling_session_id uuid,

                            paying_outlet_id uuid,
                            paying_session_id uuid,
                            paying_terminal_id uuid,

                            requested_by uuid,
                            approved_by uuid,
                            rejected_by uuid,
                            paid_by uuid,

                            approved_at timestamptz,
                            rejected_at timestamptz,
                            paid_at timestamptz,

                            rejected_reason text,
                            reason text,

                            created_at timestamptz,
                            updated_at timestamptz,
                            deleted_at timestamptz,
                            created_by uuid,
                            updated_by uuid,

                            version bigint,

                            primary key (rev, id)
);


CREATE TABLE pricing_odds_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, game_code varchar(32), bet_type varchar(32), bet_option smallint, odds numeric(12,4), active boolean, CONSTRAINT pk_pricing_odds_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_pricing_odds_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));

CREATE TABLE IF NOT EXISTS limit_assignment_aud (
                                                    id uuid NOT NULL,
                                                    rev integer NOT NULL,
                                                    revtype smallint,

                                                    tenant_id uuid,
                                                    rule_key varchar(80),

    scope_type varchar(32),
    scope_id uuid,

    enabled boolean,
    on_breach varchar(32),

    params jsonb,

    starts_at timestamptz,
    ends_at timestamptz,

    version bigint,

    created_at timestamptz,
    updated_at timestamptz,
    deleted_at timestamptz,

    PRIMARY KEY (id, rev)
    );
CREATE TABLE billing_plan_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, code varchar(128), name varchar(255), description text, price_amount numeric(19,2), currency varchar(3), billing_period varchar(50), limits_json jsonb, features_json jsonb, active boolean, is_default boolean, CONSTRAINT pk_billing_plan_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_billing_plan_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE tenant_subscription_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, plan_code varchar(128), status varchar(50), started_at timestamptz, ends_at timestamptz, trial_ends_at timestamptz, canceled_at timestamptz, metadata_json jsonb, CONSTRAINT pk_tenant_subscription_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_tenant_subscription_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE page_model_template_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, code varchar(128), logical_id varchar(255), name varchar(255), label varchar(255), description text, schema jsonb, model jsonb, schema_version integer, is_default boolean, level varchar(16), CONSTRAINT pk_page_model_template_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_page_model_template_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE page_model_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, code varchar(128), logical_id varchar(255), name varchar(255), schema jsonb, scope varchar(255), slug varchar(255), schema_version integer, model jsonb, status varchar(255), published_at timestamptz, template_id uuid, active boolean, CONSTRAINT pk_page_model_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_page_model_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE notification_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, source_type varchar(96), source_id varchar(160), dedupe_key varchar(240), audience_type varchar(32), audience_value varchar(160), severity varchar(32), kind varchar(32), category varchar(48), title_key varchar(255), message_key varchar(255), title_text varchar(512), message_text varchar(4000), payload jsonb, action_type varchar(96), action_url varchar(1024), status varchar(32), read_at timestamptz, archived_at timestamptz, expires_at timestamptz, CONSTRAINT pk_notification_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_notification_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE notification_delivery_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, notification_id uuid, channel varchar(32), recipient varchar(255), status varchar(32), attempt_count integer, next_attempt_at timestamptz, last_attempt_at timestamptz, provider varchar(96), provider_message_id varchar(160), error_code varchar(96), error_message varchar(1000), payload jsonb, CONSTRAINT pk_notification_delivery_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_notification_delivery_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
CREATE TABLE notification_preference_aud (id uuid NOT NULL,
  rev integer NOT NULL,
  revtype smallint,
  created_at timestamptz,
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  deleted_at timestamptz,
  version bigint, tenant_id uuid, scope_type varchar(32), scope_value varchar(160), category varchar(48), kind varchar(32), channel varchar(32), enabled boolean, CONSTRAINT pk_notification_preference_aud PRIMARY KEY (id, rev),
  CONSTRAINT fk_notification_preference_aud__revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev));
