http:
  routers:
    # Traefik Dashboard
    traefik-dash:
      rule: Host(`traefik.localtest.me`)
      entryPoints: [ websecure ]
      service: api@internal
      tls: { }
      middlewares: [ secure-headers@file ]

    # Keycloak SSO
    keycloak:
      rule: Host(`auth.localtest.me`)
      entryPoints: [ websecure, mobile-https ]
      service: keycloak-svc
      tls: { }
      middlewares: [ kc-iframe@file, gzip@file ]

    # Backend API
    api:
      rule: Host(`api.localtest.me`)
      entryPoints: [ websecure, mobile-https ]
      service: api-svc
      tls: { }
      middlewares: [ secure-headers@file, gzip@file ]

    # Unleash Feature Flags
    flags:
      rule: Host(`flags.localtest.me`)
      entryPoints: [ websecure ]
      service: unleash-svc
      tls: { }
      middlewares: [ secure-headers@file, gzip@file ]

    # Web App (Angular/Nx)
    web-app:
      rule: Host(`app.localtest.me`)
      entryPoints: [ websecure ]
      service: web-svc
      tls: { }
      middlewares: [ secure-headers@file, gzip@file ]

    # Mobile App (Ionic/Angular)
    mobile-app:
      rule: Host(`mob.localtest.me`)
      entryPoints: [ websecure ]
      service: mobile-svc
      tls: { }
      middlewares: [ secure-headers@file, gzip@file ]

  services:
    keycloak-svc:
      loadBalancer:
        servers:
          - url: "http://keycloak:8080"
    api-svc:
      loadBalancer:
        servers:
          - url: "http://api:8080"
    unleash-svc:
      loadBalancer:
        servers:
          - url: "http://unleash:4242"
    web-svc:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:4200"
    mobile-svc:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:4201"

# TLS Configuration pour développement local (mkcert)
tls:
  certificates:
    - certFile: /etc/traefik/certs/local-cert.pem
      keyFile: /etc/traefik/certs/local-key.pem
