log:
  level: INFO

api:
  dashboard: true
  insecure: false     # override en dev via TRAEFIK_API_INSECURE=true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

ping:
  entryPoint: "websecure"

# Let's Encrypt pour production
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@tchalanet.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
