services:
  api:
    ports:
      - "8081:8080"

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  keycloak:
    ports:
      - "8082:8080"

  unleash:
    ports:
      - "4242:4242"

  traefik:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard Traefik
    # Permettre à Traefik d'accéder à l'hôte
    extra_hosts:
      - "host.docker.internal:host-gateway"
