services:
  unleash:
    image: ${UNLEASH_IMAGE:-unleashorg/unleash-server:7.2.3}
    container_name: ${DOCKER_PREFIX:-tchl}-unleash-${ENV}
    env_file:
      - ../envs/${ENV}/.env.merged
      - ../envs/${ENV}/.secrets
    environment:
      # Connexion Postgres (on mappe nos UNLEASH_DB_* vers ce que Unleash attend)
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_SSL: 'false'

      # Config app (facultatif, à adapter)
      LOG_LEVEL: info
      NODE_ENV: production
      UNLEASH_URL: https://flags.stg.tchalanet.com
      UNLEASH_HOST: 0.0.0.0
      UNLEASH_PORT: 4242

    depends_on:
      postgres: { condition: service_healthy }
    healthcheck:
      test: ["CMD-SHELL", "(curl -fsS http://127.0.0.1:4242/health >/dev/null 2>&1) || (wget -qO- http://127.0.0.1:4242/health >/dev/null 2>&1) || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      back: {}
      edge:
        aliases: [ "unleash" ]
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: ${UNLEASH_LOG_MAX_SIZE:-10m}
        max-file: ${UNLEASH_LOG_MAX_FILES:-3}
    labels:
      - traefik.enable=${UNLEASH_TRAEFIK_ENABLE:-true}
      - traefik.docker.network=${DOCKER_NETWORK_EDGE:-edge-${ENV}}
      - traefik.http.services.unleash-svc.loadbalancer.server.port=4242
      - prometheus.scrape=true
      - prometheus.path=/api/admin/metrics
      - prometheus.port=4242

networks:
  back: {}
  edge: {}
