include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unawaited_futures: warning

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unawaited_futures: true
    use_super_parameters: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    directives_ordering: true
