http:
  routers:
    traefik-dash:
      rule: Host(`traefik.tchalanet.com`)
      entryPoints: [ websecure ]
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares: [ secure-headers@file ]

    api:
      rule: Host(`api.tchalanet.com`)
      entryPoints: [websecure]
      service: api-svc
      tls:
        certResolver: letsencrypt
      middlewares: [secure-headers@file, gzip@file]

    edge:
      rule: Host(`edge.tchalanet.com`)
      entryPoints: [websecure]
      service: edge-svc
      tls:
        certResolver: letsencrypt
      middlewares: [secure-headers@file, gzip@file]

  services:
    api-svc:
      loadBalancer:
        servers:
          - url: "http://api:8080"

    edge-svc:
      loadBalancer:
        servers:
          - url: "http://edge-service:3000"
