http:
  routers:
    api:
      rule: Host(`api.tchalanet.com`)
      entryPoints: [websecure]
      service: api-svc
      tls:
        certResolver: letsencrypt
      middlewares: [secure-headers@file, gzip@file, rate-limit-api@file]

    edge:
      rule: Host(`edge.tchalanet.com`)
      entryPoints: [websecure]
      service: edge-svc
      tls:
        certResolver: letsencrypt
      middlewares: [secure-headers@file, gzip@file, rate-limit-api@file]

  services:
    api-svc:
      loadBalancer:
        servers:
          - url: "http://api:8080"

    edge-svc:
      loadBalancer:
        servers:
          - url: "http://edge-service:3000"
