package com.tchalanet.server.core.offlinesync.internal.domain.model;

public enum OfflineTechnicalRejectReason { INVALID_SIGNATURE, PAYLOAD_HASH_MISMATCH, UNKNOWN_GRANT, GRANT_REVOKED, GRANT_EXPIRED, UNKNOWN_OFFLINE_CODE, DUPLICATE_CODE, DUPLICATE_BATCH, DUPLICATE_CLIENT_TICKET, DUPLICATE_LOCAL_SEQUENCE, SEQUENCE_GAP, TERMINAL_MISMATCH, SELLER_MISMATCH, SESSION_MISMATCH }
