package com.tchalanet.server.core.offlinesync.internal.domain.model;

public enum SalesOfflineRejectReason { LIMIT_POLICY_BLOCKED, SESSION_NOT_FOUND, SESSION_NOT_IN_GRANT, SESSION_CLOSED_BEFORE_SALE, SESSION_FINALIZED, DRAW_CUTOFF_PASSED, DRAW_ALREADY_RESULTED, SYNC_AFTER_RESULT_KNOWN, DEVICE_TIME_UNTRUSTED, PRICING_MISMATCH, MONEY_BREAKDOWN_INVALID, OFFLINE_LIMIT_EXCEEDED, DUPLICATE_ACCEPTED_OFFLINE_CODE, DUPLICATE_ACCEPTED_LOCAL_SEQUENCE, TERMINAL_LOCKED, OUTLET_SALES_BLOCKED }
