package com.tchalanet.server.common.types.id;

import java.util.UUID;

// [Phase 3C] rewrite en record conforme typed_ids §5 :
//   - class final → record
//   - uuid() → value() (auto-generated by record)
//   - of(String) → parse(String)
//   - nullableOf(UUID) ajouté
//   - random() supprimé (IdGenerator est responsable de la génération, §6)
public record PageModelId(UUID value) {

  public PageModelId {
    if (value == null) throw new IllegalArgumentException("PageModelId.value is null");
  }

  public static PageModelId of(UUID value) {
    return new PageModelId(value);
  }

  public static PageModelId nullableOf(UUID raw) {
    return raw == null ? null : new PageModelId(raw);
  }

  public static PageModelId parse(String raw) {
    if (raw == null || raw.isBlank())
      throw new IllegalArgumentException("PageModelId string is required");
    return new PageModelId(UUID.fromString(raw));
  }
}
