#!/usr/bin/env python3
import csv
from pathlib import Path

CSV = Path('src/main/resources/tchala/tchala_lotto_ht_init.csv')
OUT = Path('src/main/resources/db/migration/V29__import_tchala_lotto_ht_init.sql')

def sql_escape(s):
    if s is None:
        return ''
    return s.replace("'", "''")

rows = []
with CSV.open(encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for r in reader:
        rows.append(r)

lines = []
lines.append('-- V29__import_tchala_lotto_ht_init.sql')
lines.append('-- Generated by scripts/generate_tchala_migration.py')
lines.append('-- Idempotent import from src/main/resources/tchala/tchala_lotto_ht_init.csv')
lines.append('DO $$')
lines.append('DECLARE')
lines.append('  v_entry_id uuid;')
lines.append('BEGIN')

for r in rows:
    lang = r.get('tchala_lang','').strip()
    dream = sql_escape(r.get('dream_text','').strip())
    numbers = r.get('numbers','').strip()
    primary = r.get('primary_number','').strip()
    status = r.get('status','APPROVED').strip()
    source = sql_escape(r.get('source_name','').strip())
    source_url = sql_escape(r.get('source_url','').strip())
    dedupe = sql_escape(r.get('dedupe_key','').strip())
    notes = sql_escape(r.get('notes','').strip())

    # build numbers list
    nums = [n.strip() for n in numbers.replace(';',',').replace('|',',').split(',') if n.strip()]
    # also split by dot sequences
    if len(nums)==1:
        nums = [n.strip() for n in numbers.replace(';',',').replace('|',',').split('.') if n.strip()]

    cond = f"e.lang = '{lang}' AND e.dedupe_key = '{dedupe}' AND e.status = '{status}' AND e.canonical_entry_id IS NULL"
    lines.append(f"  IF NOT EXISTS (SELECT 1 FROM tchala_entry e WHERE {cond}) THEN")
    lines.append("    v_entry_id := gen_random_uuid();")
    lines.append("    INSERT INTO tchala_entry (id, lang, dream, dedupe_key, note, status, source, created_at, updated_at) VALUES (\")
    lines.append(f"      v_entry_id, '{lang}', '{dream}', '{dedupe}', '{notes}', '{status}', '{source}', now(), now());")
    for n in nums:
        # ensure numeric and 0..99
        nn = n.lstrip('0') or '0'
        try:
            intval = int(nn)
        except:
            continue
        if intval < 0 or intval > 99:
            continue
        lines.append(f"    INSERT INTO tchala_entry_number (entry_id, lang, number) VALUES (v_entry_id, '{lang}', {intval}) ON CONFLICT DO NOTHING;")
    lines.append('  END IF;')

lines.append('END$$;')

OUT.parent.mkdir(parents=True, exist_ok=True)
with OUT.open('w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(f'Wrote migration to {OUT}')
