package com.tchalanet.server.core.sales.api.model.promotion;

/**
 * Indicates why a ticket line exists.
 * <p>
 * CUSTOMER:
 * A normal line paid by the buyer.
 * <p>
 * PROMOTION:
 * A line generated by a promotion, for example MARYAJ_GRATUIT
 * or "5 boules achetées + 2 gratuites".
 */
public enum TicketLineOrigin {
    CUSTOMER,
    PROMOTION
}
