package com.tchalanet.server.core.limitpolicy.domain.model;

public enum RuleKey {
  MAX_STAKE_PER_LINE,
  MIN_STAKE_PER_LINE,
  MAX_LINES_PER_TICKET,
  MAX_STAKE_PER_TICKET,
  MAX_STAKE_PER_SELECTION_PER_TICKET,
  MAX_SALES_COUNT_PER_SELECTION_PER_DRAW,
  MAX_EXPOSURE_PER_SELECTION_PER_DRAW,
  MAX_TOTAL_STAKE_PER_DRAW,
  MAX_POTENTIAL_PAYOUT_EXPOSURE_PER_SELECTION_PER_DRAW,
  DAILY_STAKE_CAP,
  DAILY_PAYOUT_CAP,
  MAX_CANCELS_PER_DAY,
  MAX_PAYOUT_PER_LINE,
  MAX_PAYOUT_PER_TICKET
}
