http:
  routers:
    # UI Admin (facultatif en local ; conseillé en stg)
    flags:
      rule: Host(`flags.localtest.me`)
      entryPoints: [ websecure ]
      service: unleash-svc
      tls: {}
      middlewares: [ secure-headers@file, gzip@file ]

  services:
    # accès interne au server
    unleash-svc:
      loadBalancer:
        servers:
          - url: "http://unleash:4242"

