name: Docs CI

on:
  push:
    branches: [main]
    paths:
      - 'tchalanet-docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'tchalanet-docs/**'
      - '.github/workflows/docs.yml'

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build MkDocs

    defaults:
      run:
        working-directory: tchalanet-docs

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install mkdocs deps
        run: |
          pip install -r requirements.txt

      - name: Build docs (strict)
        run: mkdocs build --strict

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install mkdocs deps
        run: pip install -r requirements.txt

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: mkdocs gh-deploy --force
