name: CI - Tchalanet mobile

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'tchalanet-mobile/'
      - '.github/workflows/mobile_c_i_c_d.yml'
  pull_request:
    paths:
      - 'tchalanet-mobile/'
      - '.github/workflows/mobile_c_i_c_d.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tchalanet-mobile

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'tchalanet-mobile/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Build Web
        run: npm run build -- --configuration=production

      - name: Set up JDK for Android builds
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Ionic & Capacitor
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') }}
        run: npm install -g @ionic/cli @capacitor/cli

      - name: Build Android
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') }}
        run: |
          ionic capacitor sync android
          cd android
          ./gradlew assembleDebug

      - name: Upload Android APK
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') }}
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: tchalanet-mobile/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
