name: CI-CD tchalanet-server

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tchalanet-server
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Maven verify (lint+tests)
        run: mvn -B -DskipITs=false verify

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./tchalanet-server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tchalanet-server:sha-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/tchalanet-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-staging:
    needs: [build-api]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: ssh://deploy@staging.tchalanet.ht
    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}

      - name: Pull & Up on remote host (staging)
        run: |
          cd tchalanet-infra
          API_TAG=sha-${GITHUB_SHA} \
          docker compose --env-file envs/staging/.env \
            -f docker-compose.yml -f docker-compose.prod.yml \
            pull api && \
          API_TAG=sha-${GITHUB_SHA} \
          docker compose --env-file envs/staging/.env \
            -f docker-compose.yml -f docker-compose.prod.yml \
            up -d

  release-prod:
    needs: [build-api]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: ssh://deploy@prod.tchalanet.ht
    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Compute version tag
        id: ver
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Retag & push semver
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/tchalanet-server:sha-${GITHUB_SHA}
          docker tag ghcr.io/${{ github.repository_owner }}/tchalanet-server:sha-${GITHUB_SHA} \
                    ghcr.io/${{ github.repository_owner }}/tchalanet-server:${{ steps.ver.outputs.TAG }}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/tchalanet-server:${{ steps.ver.outputs.TAG }}

      - name: Deploy prod
        run: |
          cd tchalanet-infra
          API_TAG=${{ steps.ver.outputs.TAG }} \
          docker compose --env-file envs/prod/.env \
            -f docker-compose.yml -f docker-compose.prod.yml \
            pull api && \
          API_TAG=${{ steps.ver.outputs.TAG }} \
          docker compose --env-file envs/prod/.env \
            -f docker-compose.yml -f docker-compose.prod.yml \
            up -d
