name: CI - Tchalanet Web

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'tchalanet-web/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'tchalanet-web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tchalanet-web

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'tchalanet-web/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: tchalanet-web/dist/apps/web
